# MANUAL DELETES: rateLimiter, .envConfig, compose.txt

# docker-compose up --build -d 
services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_AUD: ${PGRST_JWT_AUD}
    depends_on:
      - database