# MANUAL DELETES: rateLimiter, .envConfig, compose.txt

# docker-compose up --build -d services:
services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/

  postgrest:
    image: postgrest/postgrest
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_AUD: ${PGRST_JWT_AUD}
    depends_on:
      - database

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sourcecode-dckimg
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    depends_on:
      - database
      - postgrest
    #volumes:      
    #- ./src:/src 

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - postgrest